export const JUEGOS_POR_NOMBRE = "JUEGOS_POR_NOMBRE";
export const TODOS_LOS_JUEGOS = "TODOS_LOS_JUEGOS";
export const GENERO = "GENERO";
export const ORDENAR = "ORDENAR";
export const ORDENAR_POR_NOMBRE = "ORDENAR_POR_NOMBRE";
export const ORDENAR_POR_RATING = "ORDENAR_POR_RATING";